import { Metadata } from "next";
import {
  APP_NAME,
  AUTH_NAME,
  DB_NAME,
  DEVELOPER_DOMAIN,
} from "../../../constants";
import H1 from "@/components/ui/h1";
import { H2 } from "@/components/ui/H2";

export const metadata: Metadata = {
  title: "Privacy Policy",
};

const updateDate = "November 2024";

export default function Page() {
  return (
    <section className="space-y-6">
      <div className="container mx-auto mt-6 space-y-6 p-4">
        <div className="space-y-3">
          <H1>Privacy Policy For &quot;{APP_NAME}&quot; Website</H1>
          <p>Last Updated: {updateDate}</p>
        </div>
        <div className="space-y-3">
          <H2>Introduction</H2>
          <p>
            Welcome to the {APP_NAME} website. This Privacy Policy outlines our
            practices regarding the collection, use, and disclosure of
            information that we receive through our website. Our primary goal is
            to provide you with a convenient tool while respecting your privacy.
          </p>
          <H2>Information We Collect</H2>
          <p>
            We collect the following personal data when you use the {APP_NAME}{" "}
            website:
          </p>
          <ul>
            <li>
              <strong>Email</strong>: Collected through {AUTH_NAME} for
              authentication purposes.
            </li>
            <li>
              <strong>User ID</strong>: A unique identifier generated by{" "}
              {AUTH_NAME}
              to associate your account with your data.
            </li>
            <li>
              <strong>Investments</strong>: Titles and content of your personal
              investments are stored in our backend database.
            </li>
          </ul>

          <H2>Data Storage and Security</H2>
          <p>
            Your investments and related data are securely stored in{" "}
            <a
              href="https://vercel.com/docs/storage/vercel-postgres#vercel-postgres"
              target="_blank"
              rel="noopener noreferrer"
            >
              {DB_NAME}
            </a>
            , a widely used, industry-standard serverless SQL database.{" "}
            {DB_NAME} is known for its robust security features, and we use it
            to ensure your data is stored safely.
          </p>
          <p>
            Additionally, you can delete your data anytime through the website
            or by visiting our{" "}
            <a href="/instruction">Account Deletion Instructions</a> page for
            detailed steps on how to delete your account and all associated
            data.
          </p>

          <H2>Use of Information</H2>
          <p>
            - <strong>Email and User ID</strong>: These are used to authenticate
            and identify you within the website.
            <br />- <strong>Investments</strong>: Your personal investment
            records, including their title and content, are stored to provide
            you with the ability to view, edit, and manage your investments
            across sessions.
          </p>
          <H2>Data Retention and Deletion</H2>
          <p>
            - <strong>Personal Data</strong>: The personal data we collect
            (email, user ID, and investments) is stored securely by our
            third-party services. Your email is stored on {AUTH_NAME}&apos;s
            servers, while your user ID and investment records are stored on{" "}
            {DB_NAME}&apos;s servers.
          </p>
          <p>
            - <strong>Investment Management</strong>: You can delete any of your
            investments at any time within the website. Once deleted, they are
            permanently removed from our database.
          </p>
          <p>
            - <strong>Account Deletion</strong>: You can delete your account and
            all associated data by following the instructions on our{" "}
            <a href="/instruction">Account Deletion Instructions</a> page. To
            manage your account details (such as updating your email), log in to
            the app and navigate to the account button at the top of the{" "}
            <a href="/investments">Investments</a> page. From there, select
            &quot;Manage account&quot; to access account management options
            provided by
            {AUTH_NAME}. Please note that deleting your account via {AUTH_NAME}{" "}
            only removes your account details, but not your investment records.
            To delete your account along with your investment records, follow
            the instructions on our account deletion page. After deleting your
            account, all associated data, including your email, user ID, and
            investment records, will be permanently removed.
          </p>
          <H2>Data Sharing and Disclosure</H2>
          <p>
            We do not sell, trade, or rent your personal identification
            information to others. We may share some information with
            third-party services like {AUTH_NAME} for authentication purposes,
            but we ensure that any data shared is handled securely and in
            compliance with applicable privacy laws.
          </p>
          <p>
            We use{" "}
            <a
              href="https://clerk.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              {AUTH_NAME}
            </a>
            , a third-party authentication service, to manage user
            authentication and account creation. {AUTH_NAME} securely handles
            your login credentials, including your email, and generates a unique
            user ID for your account. {AUTH_NAME} complies with
            industry-standard security practices to ensure your data is
            protected.
          </p>

          <H2>Security</H2>
          <p>
            We take your privacy and the security of your data seriously. All
            user data is stored securely, and we implement industry-standard
            security practices to protect your information to the best extent
            possible.
          </p>
          <H2>Account Termination</H2>
          <p>
            You can delete your account and all associated data by following the
            instructions on our{" "}
            <a href="/instruction">Account Deletion Instructions</a> page.
          </p>

          <H2>Changes to This Privacy Policy</H2>
          <p>
            This Privacy Policy is effective as of {updateDate} and will remain
            in effect except with respect to any changes in its provisions in
            the future, which will be in effect immediately after being posted
            on this page. We reserve the right to update or change our Privacy
            Policy at any time, and you should check this Privacy Policy
            periodically.
          </p>
          <H2>Contact Us</H2>
          <p>
            If you have any questions about this Privacy Policy, please contact
            us at{" "}
            <a href={`mailto:support@${DEVELOPER_DOMAIN}`}>
              support@{DEVELOPER_DOMAIN}
            </a>
            .
          </p>
        </div>
      </div>
    </section>
  );
}
